name: Run Python Script

on:
  schedule:
    - cron: '0 0 * * *'  # This runs the script daily at midnight UTC

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-activate-base: false

    - name: Create and activate conda environment
      run: |
        conda env create --file environment.yml
        conda activate myenv  # Replace `myenv` with your environment name if different
        
    - name: Install dependencies
      run: |
        conda env update --file environment.yml --name base
        conda activate base  # Activate the `base` environment

    - name: Run Python script
      run: |
        python scripts/my_script.py  # Path to your Python script
